name: Запуск бота

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Клонируем репозиторий
        uses: actions/checkout@v4

      - name: Устанавливаем зависимости
        run: pip install -r requirements.txt

      - name: Запускаем бота
        run: python fondelete_bot/bot.py
